# Generated by Django 6.0.5 on 2026-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='meeting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
